export * from './dashboard/Dashboard'
export * from './login/Login'
export * from './pessoas/ListagemPessoas'
export * from './pessoas/DetalhePessoas'
export * from './cidades/ListagemCidades'
export * from './cidades/DetalheCidades'